export declare const maxWidth38x = 380;
export declare const maxWidth45x = 450;
export declare const maxWidth6xx = 600;
export declare const maxWidth7xx = 700;
export declare const maxWidth8xx = 800;
export declare const maxHeight6xx = 600;
export declare const maxHeight8xx = 800;
export declare const maxWidth11xx = 1100;
export declare const queryMaxWidth38x: string;
export declare const queryMaxWidth45x: string;
export declare const queryMaxWidth6xx: string;
export declare const queryMaxWidth7xx: string;
export declare const queryMaxWidth8xx: string;
export declare const queryMaxHeight6xx: string;
export declare const queryMaxHeight8xx: string;
export declare const queryMaxWidth11xx: string;
